### ISSUE TITLE
When will the results be made available

### ISSUE THREAD

**Issue by oserikov** [lingjzhu/clap-ipa#1]
Dear authors! Impressed by your work I wanted to integrate your methods to my research pipeline. However, results are not available. Can I get some insights to maybe preliminary version of the it?

**Comment by lingjzhu** [comment]
thank you! this paper is under review and, because of the anonimity policy, we might not be able to share until the review period is concluded. I think we will begin releasing data, models and scripts at around March.

**Comment by korakot** [comment]
Looking forward to test the model and explore the data. Thanks for the update.
